In [1]:
import pandas as pd
dfN = pd.read_csv('Trump_nodes.csv')
dfE = pd.read_csv('Trump_edges.csv')

In [2]:
dfN

                      Id            Label  Followers   Lang
0              338153973      SoonerSower       1167     en
1              148471361       racephenom      17663     en
2              216346234        Hugorelly       3296     en
3     777472984160333828    RachelMann123        419  en-gb
4             2952468264  SolidPerspectiv       4540     en
5               33256808  TaxReformExpert      16674     en
6               87983041       UROCKlive1      52380     en
7               32871086     kylegriffin1     529677     en
8                3108351              WSJ   16324412     en
9               26487169         LouDobbs    1873067     en
10            3469891942       ElvaNicely          7     en
11             119815003          Coolaga        131     en
12   1045732627913814017     PatriotMAGAx       2500     en
13            1623117289         MiscMona        903     en
14             956349186    jasonmparsons      11258     en
15             118576470       OkCallMeAL      28276     en
16            2911249548          psajazz        231     en
17             765980521   RTPTravelAgent        346     en
18              24054724       lparker922       1337     en
19              20562505       toospecial        149     en
20            3333055535       EricHolder     450215     en
21              16708240         donna816       1254     en
22             580312540  girlsreallyrule     181998     en
23             209274991      PinkBelgium      34711     fr
24    753694962815004673        katdd9999       2564     en
25    754055601936736256   stephensinglet       1442     en
26            3383496622  RightToBearPuns        256     en
27    825955586705469440   ParuchGretchen        864     en
28              18217345      caroljeanne       1756     en
29              39052087    BobBourgeault       2098     en
..                   ...              ...        ...    ...
860            426802833      AP_Politics     355268     en
861            405341045        Heywood98      19269     en
862   712477970967953409     Vii_Martinss        288     en
863           2800581040      BillKristol     435741     en
864           2173330902      YichunWang1        549     en
865             18166778       Jim_Jordan     401855     en
866             32920372         salfonsi        391     en
867  1038373635856236545  OfficialPTWStev       1408     en
868            190260040        paronlulu       3185     en
869   940663755607826432         ruthcmay        436     en
870   757358178044678144   ungubunugu1274       1614     de
871              6700382  ViewFromEngland       7091  en-gb
872            559084467      _lolacarter        670     pt
873            459765878        firefan17       8880     en
874           3434655454    david58573348        688     en
875             29138875         rustytwr         24     en
876             14855994      davidsirota     122348     en
877            329227823       pitter1311         65     en
878            274603425         Domidest        125     da
879            372536101  NatashaBertrand     379711     en
880           4854822338   lovealaska1105       4180     en
881             16012783    thedailybeast    1200767     en
882           3686488635   Easterndmondbk       3705     en
883  1049475664804532225    BulwarkOnline      10750     en
884             14173315          NBCNews    6350096     en
885            600512429        Baby_Xmas        162     en
886            156726012         morlingg        118     en
887             14717197              TPM     276863     en
888             23332368     Resistmybutt       4013     en
889           1152105936  StockBoardAsset      18810     en

[890 rows x 4 columns]

In [3]:
dfE

                  Source               Target                 Time
0               16260425           2347049341  2019-01-18 14:08:03
1             3343598465           3223426134  2019-01-18 14:08:03
2              258607042             84195118  2019-01-18 14:08:03
3               35287204             16246688  2019-01-18 14:08:04
4              335576999           2467720274  2019-01-18 14:08:04
5             1260458809            150078976  2019-01-18 14:08:04
6              428823129            390458956  2019-01-18 14:08:04
7     879092788771430400             14247236  2019-01-18 14:08:04
8              269870372              2836421  2019-01-18 14:08:04
9     902991579706732544            132339474  2019-01-18 14:08:04
10            2198337368             14247236  2019-01-18 14:08:04
11             107499344              4207961  2019-01-18 14:08:03
12              58209923             49698134  2019-01-18 14:08:03
13             450174247   759481842814726144  2019-01-18 14:08:04
14    896003463922020352           1286161147  2019-01-18 14:08:04
15            1360790161           1717674524  2019-01-18 14:08:04
16   1005665677750030336           4775059214  2019-01-18 14:08:04
17            1681616449            231510077  2019-01-18 14:08:04
18             295642835             39279821  2019-01-18 14:08:04
19    710489142996631552   975848721110855680  2019-01-18 14:08:04
20    986009137875107841           4091551984  2019-01-18 14:08:04
21             203227956            289111175  2019-01-18 14:08:04
22              23482145             14717197  2019-01-18 14:08:04
23            3320095912   997098335747084289  2019-01-18 14:08:04
24               4341601   845392971381927936  2019-01-18 14:08:04
25    701412529839411200           1674315427  2019-01-18 14:08:04
26             909504800           1020058453  2019-01-18 14:08:04
27            4780029508            172511244  2019-01-18 14:08:04
28            3007139824            390170244  2019-01-18 14:08:04
29            1377995232             51241574  2019-01-18 14:08:04
..                   ...                  ...                  ...
559            330075517            150078976  2019-01-18 14:08:19
560  1069378977037336576   856596564516651008  2019-01-18 14:08:19
561             25571493             16041234  2019-01-18 14:08:20
562           2203159998            158426909  2019-01-18 14:08:19
563  1067462769312714752              8363752  2019-01-18 14:08:20
564             37953356             63270681  2019-01-18 14:08:20
565            467488893   926678101253345280  2019-01-18 14:08:20
566   781338327924473856             14146966  2019-01-18 14:08:20
567            203056990            132339474  2019-01-18 14:08:20
568  1075156620626280449             15976705  2019-01-18 14:08:20
569             15713194            548384458  2019-01-18 14:08:20
570   867594960417239040            931286316  2019-01-18 14:08:20
571           3383496622           2347049341  2019-01-18 14:08:20
572   822861082305896448           2327400218  2019-01-18 14:08:20
573            447283713  1049475664804532225  2019-01-18 14:08:20
574  1004910634448941056             26487169  2019-01-18 14:08:20
575           3096554448             22187085  2019-01-18 14:08:20
576  1084107073145589760   774407512598704128  2019-01-18 14:08:20
577             44534596             14247236  2019-01-18 14:08:20
578            329185762            580224794  2019-01-18 14:08:20
579           2548750220            518254771  2019-01-18 14:08:20
580           2495196338              9300262  2019-01-18 14:08:20
581           4614299435   764289800127979520  2019-01-18 14:08:20
582   868988700205731840           2421067430  2019-01-18 14:08:20
583            198878889            132339474  2019-01-18 14:08:20
584            551890101   711627609344516096  2019-01-18 14:08:20
585             12811472            535643852  2019-01-18 14:08:20
586           1640796859             25073877  2019-01-18 14:08:20
587   998294687784972289            232901331  2019-01-18 14:08:20
588             19570817           2863996955  2019-01-18 14:08:20

[589 rows x 3 columns]

In [4]:
dfN['SeqId']=range(1,len(dfN)+1)

In [5]:
dfNsimple=dfN.drop(['Label','Followers','Lang'],axis=1)

In [6]:
dfNsimple

                      Id  SeqId
0              338153973      1
1              148471361      2
2              216346234      3
3     777472984160333828      4
4             2952468264      5
5               33256808      6
6               87983041      7
7               32871086      8
8                3108351      9
9               26487169     10
10            3469891942     11
11             119815003     12
12   1045732627913814017     13
13            1623117289     14
14             956349186     15
15             118576470     16
16            2911249548     17
17             765980521     18
18              24054724     19
19              20562505     20
20            3333055535     21
21              16708240     22
22             580312540     23
23             209274991     24
24    753694962815004673     25
25    754055601936736256     26
26            3383496622     27
27    825955586705469440     28
28              18217345     29
29              39052087     30
..                   ...    ...
860            426802833    861
861            405341045    862
862   712477970967953409    863
863           2800581040    864
864           2173330902    865
865             18166778    866
866             32920372    867
867  1038373635856236545    868
868            190260040    869
869   940663755607826432    870
870   757358178044678144    871
871              6700382    872
872            559084467    873
873            459765878    874
874           3434655454    875
875             29138875    876
876             14855994    877
877            329227823    878
878            274603425    879
879            372536101    880
880           4854822338    881
881             16012783    882
882           3686488635    883
883  1049475664804532225    884
884             14173315    885
885            600512429    886
886            156726012    887
887             14717197    888
888             23332368    889
889           1152105936    890

[890 rows x 2 columns]

In [7]:
dfT=pd.merge(dfE, dfNsimple, left_on='Source', right_on='Id')

In [8]:
dfT

,Source,Target,Time,Id,SeqId
0,16260425,2347049341,2019-01-18 14:08:03,16260425,62
1,3343598465,3223426134,2019-01-18 14:08:03,3343598465,718
2,258607042,84195118,2019-01-18 14:08:03,258607042,253
3,35287204,16246688,2019-01-18 14:08:04,35287204,262
4,335576999,2467720274,2019-01-18 14:08:04,335576999,44
5,1260458809,150078976,2019-01-18 14:08:04,1260458809,564
6,428823129,390458956,2019-01-18 14:08:04,428823129,383
7,879092788771430400,14247236,2019-01-18 14:08:04,879092788771430400,358
8,269870372,2836421,2019-01-18 14:08:04,269870372,591
9,902991579706732544,132339474,2019-01-18 14:08:04,902991579706732544,395
10,2198337368,14247236,2019-01-18 14:08:04,2198337368,612
11,107499344,4207961,2019-01-18 14:08:03,107499344,174
12,58209923,49698134,2019-01-18 14:08:03,58209923,567
13,58209923,40996128,2019-01-18 14:08:13,58209923,567
14,450174247,759481842814726144,2019-01-18 14:08:04,450174247,859
15,896003463922020352,1286161147,2019-01-18 14:08:04,896003463922020352,65
16,1360790161,1717674524,2019-01-18 14:08:04,1360790161,457
17,1005665677750030336,4775059214,2019-01-18 14:08:04,1005665677750030336,580
18,1681616449,231510077,2019-01-18 14:08:04,1681616449,559
19,295642835,39279821,2019-01-18 14:08:04,295642835,778
20,710489142996631552,975848721110855680,2019-01-18 14:08:04,710489142996631552,301
21,986009137875107841,4091551984,2019-01-18 14:08:04,986009137875107841,184
22,986009137875107841,755057897583804416,2019-01-18 14:08:11,986009137875107841,184
23,203227956,289111175,2019-01-18 14:08:04,203227956,69
24,23482145,14717197,2019-01-18 14:08:04,23482145,469
25,3320095912,997098335747084289,2019-01-18 14:08:04,3320095912,112
26,4341601,845392971381927936,2019-01-18 14:08:04,4341601,430
27,701412529839411200,1674315427,2019-01-18 14:08:04,701412529839411200,754
28,909504800,1020058453,2019-01-18 14:08:04,909504800,243
29,4780029508,172511244,2019-01-18 14:08:04,4780029508,824
...,...,...,...,...,...
559,796619447209365504,833224452787761152,2019-01-18 14:08:19,796619447209365504,136
560,49220743,242555999,2019-01-18 14:08:19,49220743,772
561,351754122,132339474,2019-01-18 14:08:19,351754122,165
562,971020804744994817,528999980,2019-01-18 14:08:19,971020804744994817,486
563,330075517,150078976,2019-01-18 14:08:19,330075517,295
564,25571493,16041234,2019-01-18 14:08:20,25571493,389
565,1067462769312714752,8363752,2019-01-18 14:08:20,1067462769312714752,169
566,37953356,63270681,2019-01-18 14:08:20,37953356,47
567,467488893,926678101253345280,2019-01-18 14:08:20,467488893,326
568,781338327924473856,14146966,2019-01-18 14:08:20,781338327924473856,701
569,203056990,132339474,2019-01-18 14:08:20,203056990,418
570,1075156620626280449,15976705,2019-01-18 14:08:20,1075156620626280449,631
571,867594960417239040,931286316,2019-01-18 14:08:20,867594960417239040,717
572,3383496622,2347049341,2019-01-18 14:08:20,3383496622,27
573,822861082305896448,2327400218,2019-01-18 14:08:20,822861082305896448,361
574,447283713,1049475664804532225,2019-01-18 14:08:20,447283713,599
575,1004910634448941056,26487169,2019-01-18 14:08:20,1004910634448941056,338
576,3096554448,22187085,2019-01-18 14:08:20,3096554448,499
577,1084107073145589760,774407512598704128,2019-01-18 14:08:20,1084107073145589760,170
578,44534596,14247236,2019-01-18 14:08:20,44534596,307
579,329185762,580224794,2019-01-18 14:08:20,329185762,779
580,2548750220,518254771,2019-01-18 14:08:20,2548750220,569
581,4614299435,764289800127979520,2019-01-18 14:08:20,4614299435,123
582,868988700205731840,2421067430,2019-01-18 14:08:20,868988700205731840,261
583,198878889,132339474,2019-01-18 14:08:20,198878889,579
584,551890101,711627609344516096,2019-01-18 14:08:20,551890101,745
585,12811472,535643852,2019-01-18 14:08:20,12811472,100
586,1640796859,25073877,2019-01-18 14:08:20,1640796859,244
587,998294687784972289,232901331,2019-01-18 14:08:20,998294687784972289,661
588,19570817,2863996955,2019-01-18 14:08:20,19570817,438

In [9]:
dfT['Source']= dfT['SeqId']
del dfT['SeqId']
del dfT['Id']

In [10]:
dfT

     Source               Target                 Time
0        62           2347049341  2019-01-18 14:08:03
1       718           3223426134  2019-01-18 14:08:03
2       253             84195118  2019-01-18 14:08:03
3       262             16246688  2019-01-18 14:08:04
4        44           2467720274  2019-01-18 14:08:04
5       564            150078976  2019-01-18 14:08:04
6       383            390458956  2019-01-18 14:08:04
7       358             14247236  2019-01-18 14:08:04
8       591              2836421  2019-01-18 14:08:04
9       395            132339474  2019-01-18 14:08:04
10      612             14247236  2019-01-18 14:08:04
11      174              4207961  2019-01-18 14:08:03
12      567             49698134  2019-01-18 14:08:03
13      567             40996128  2019-01-18 14:08:13
14      859   759481842814726144  2019-01-18 14:08:04
15       65           1286161147  2019-01-18 14:08:04
16      457           1717674524  2019-01-18 14:08:04
17      580           4775059214  2019-01-18 14:08:04
18      559            231510077  2019-01-18 14:08:04
19      778             39279821  2019-01-18 14:08:04
20      301   975848721110855680  2019-01-18 14:08:04
21      184           4091551984  2019-01-18 14:08:04
22      184   755057897583804416  2019-01-18 14:08:11
23       69            289111175  2019-01-18 14:08:04
24      469             14717197  2019-01-18 14:08:04
25      112   997098335747084289  2019-01-18 14:08:04
26      430   845392971381927936  2019-01-18 14:08:04
27      754           1674315427  2019-01-18 14:08:04
28      243           1020058453  2019-01-18 14:08:04
29      824            172511244  2019-01-18 14:08:04
..      ...                  ...                  ...
559     136   833224452787761152  2019-01-18 14:08:19
560     772            242555999  2019-01-18 14:08:19
561     165            132339474  2019-01-18 14:08:19
562     486            528999980  2019-01-18 14:08:19
563     295            150078976  2019-01-18 14:08:19
564     389             16041234  2019-01-18 14:08:20
565     169              8363752  2019-01-18 14:08:20
566      47             63270681  2019-01-18 14:08:20
567     326   926678101253345280  2019-01-18 14:08:20
568     701             14146966  2019-01-18 14:08:20
569     418            132339474  2019-01-18 14:08:20
570     631             15976705  2019-01-18 14:08:20
571     717            931286316  2019-01-18 14:08:20
572      27           2347049341  2019-01-18 14:08:20
573     361           2327400218  2019-01-18 14:08:20
574     599  1049475664804532225  2019-01-18 14:08:20
575     338             26487169  2019-01-18 14:08:20
576     499             22187085  2019-01-18 14:08:20
577     170   774407512598704128  2019-01-18 14:08:20
578     307             14247236  2019-01-18 14:08:20
579     779            580224794  2019-01-18 14:08:20
580     569            518254771  2019-01-18 14:08:20
581     123   764289800127979520  2019-01-18 14:08:20
582     261           2421067430  2019-01-18 14:08:20
583     579            132339474  2019-01-18 14:08:20
584     745   711627609344516096  2019-01-18 14:08:20
585     100            535643852  2019-01-18 14:08:20
586     244             25073877  2019-01-18 14:08:20
587     661            232901331  2019-01-18 14:08:20
588     438           2863996955  2019-01-18 14:08:20

[589 rows x 3 columns]

In [11]:
dfEout=pd.merge(dfT, dfNsimple, left_on='Target', right_on='Id')

In [12]:
dfEout

,Source,Target,Time,Id,SeqId
0,62,2347049341,2019-01-18 14:08:03,2347049341,234
1,518,2347049341,2019-01-18 14:08:06,2347049341,234
2,530,2347049341,2019-01-18 14:08:06,2347049341,234
3,148,2347049341,2019-01-18 14:08:14,2347049341,234
4,27,2347049341,2019-01-18 14:08:20,2347049341,234
5,718,3223426134,2019-01-18 14:08:03,3223426134,420
6,339,3223426134,2019-01-18 14:08:08,3223426134,420
7,747,3223426134,2019-01-18 14:08:12,3223426134,420
8,481,3223426134,2019-01-18 14:08:16,3223426134,420
9,253,84195118,2019-01-18 14:08:03,84195118,640
10,520,84195118,2019-01-18 14:08:07,84195118,640
11,108,84195118,2019-01-18 14:08:11,84195118,640
12,550,84195118,2019-01-18 14:08:13,84195118,640
13,262,16246688,2019-01-18 14:08:04,16246688,556
14,210,16246688,2019-01-18 14:08:08,16246688,556
15,44,2467720274,2019-01-18 14:08:04,2467720274,621
16,564,150078976,2019-01-18 14:08:04,150078976,278
17,816,150078976,2019-01-18 14:08:06,150078976,278
18,118,150078976,2019-01-18 14:08:09,150078976,278
19,295,150078976,2019-01-18 14:08:19,150078976,278
20,383,390458956,2019-01-18 14:08:04,390458956,49
21,358,14247236,2019-01-18 14:08:04,14247236,538
22,612,14247236,2019-01-18 14:08:04,14247236,538
23,872,14247236,2019-01-18 14:08:05,14247236,538
24,672,14247236,2019-01-18 14:08:05,14247236,538
25,43,14247236,2019-01-18 14:08:07,14247236,538
26,82,14247236,2019-01-18 14:08:07,14247236,538
27,79,14247236,2019-01-18 14:08:09,14247236,538
28,616,14247236,2019-01-18 14:08:09,14247236,538
29,213,14247236,2019-01-18 14:08:09,14247236,538
...,...,...,...,...,...
559,83,224383563,2019-01-18 14:08:18,224383563,258
560,437,40129171,2019-01-18 14:08:18,40129171,602
561,750,15757578,2019-01-18 14:08:18,15757578,522
562,781,136300373,2019-01-18 14:08:18,136300373,776
563,153,19087651,2019-01-18 14:08:18,19087651,127
564,175,580224794,2019-01-18 14:08:18,580224794,135
565,779,580224794,2019-01-18 14:08:20,580224794,135
566,18,1037321378,2019-01-18 14:08:18,1037321378,693
567,312,81432933,2019-01-18 14:08:18,81432933,181
568,871,384913290,2019-01-18 14:08:19,384913290,552
569,690,136487125,2019-01-18 14:08:19,136487125,690
570,40,823201687867420672,2019-01-18 14:08:19,823201687867420672,74
571,168,881336677138128897,2019-01-18 14:08:19,881336677138128897,847
572,704,780206406024691712,2019-01-18 14:08:19,780206406024691712,502
573,686,61015562,2019-01-18 14:08:19,61015562,470
574,330,92408522,2019-01-18 14:08:19,92408522,99
575,143,732515283902943232,2019-01-18 14:08:19,732515283902943232,464
576,136,833224452787761152,2019-01-18 14:08:19,833224452787761152,431
577,486,528999980,2019-01-18 14:08:19,528999980,487
578,389,16041234,2019-01-18 14:08:20,16041234,523
579,326,926678101253345280,2019-01-18 14:08:20,926678101253345280,605
580,701,14146966,2019-01-18 14:08:20,14146966,748
581,631,15976705,2019-01-18 14:08:20,15976705,229
582,361,2327400218,2019-01-18 14:08:20,2327400218,155
583,599,1049475664804532225,2019-01-18 14:08:20,1049475664804532225,884
584,338,26487169,2019-01-18 14:08:20,26487169,10
585,569,518254771,2019-01-18 14:08:20,518254771,328
586,123,764289800127979520,2019-01-18 14:08:20,764289800127979520,817
587,745,711627609344516096,2019-01-18 14:08:20,711627609344516096,849
588,438,2863996955,2019-01-18 14:08:20,2863996955,678

In [13]:
dfEout['Target']= dfEout['SeqId']
del dfEout['SeqId']
del dfEout['Id']

In [14]:
dfEout

     Source  Target                 Time
0        62     234  2019-01-18 14:08:03
1       518     234  2019-01-18 14:08:06
2       530     234  2019-01-18 14:08:06
3       148     234  2019-01-18 14:08:14
4        27     234  2019-01-18 14:08:20
5       718     420  2019-01-18 14:08:03
6       339     420  2019-01-18 14:08:08
7       747     420  2019-01-18 14:08:12
8       481     420  2019-01-18 14:08:16
9       253     640  2019-01-18 14:08:03
10      520     640  2019-01-18 14:08:07
11      108     640  2019-01-18 14:08:11
12      550     640  2019-01-18 14:08:13
13      262     556  2019-01-18 14:08:04
14      210     556  2019-01-18 14:08:08
15       44     621  2019-01-18 14:08:04
16      564     278  2019-01-18 14:08:04
17      816     278  2019-01-18 14:08:06
18      118     278  2019-01-18 14:08:09
19      295     278  2019-01-18 14:08:19
20      383      49  2019-01-18 14:08:04
21      358     538  2019-01-18 14:08:04
22      612     538  2019-01-18 14:08:04
23      872     538  2019-01-18 14:08:05
24      672     538  2019-01-18 14:08:05
25       43     538  2019-01-18 14:08:07
26       82     538  2019-01-18 14:08:07
27       79     538  2019-01-18 14:08:09
28      616     538  2019-01-18 14:08:09
29      213     538  2019-01-18 14:08:09
..      ...     ...                  ...
559      83     258  2019-01-18 14:08:18
560     437     602  2019-01-18 14:08:18
561     750     522  2019-01-18 14:08:18
562     781     776  2019-01-18 14:08:18
563     153     127  2019-01-18 14:08:18
564     175     135  2019-01-18 14:08:18
565     779     135  2019-01-18 14:08:20
566      18     693  2019-01-18 14:08:18
567     312     181  2019-01-18 14:08:18
568     871     552  2019-01-18 14:08:19
569     690     690  2019-01-18 14:08:19
570      40      74  2019-01-18 14:08:19
571     168     847  2019-01-18 14:08:19
572     704     502  2019-01-18 14:08:19
573     686     470  2019-01-18 14:08:19
574     330      99  2019-01-18 14:08:19
575     143     464  2019-01-18 14:08:19
576     136     431  2019-01-18 14:08:19
577     486     487  2019-01-18 14:08:19
578     389     523  2019-01-18 14:08:20
579     326     605  2019-01-18 14:08:20
580     701     748  2019-01-18 14:08:20
581     631     229  2019-01-18 14:08:20
582     361     155  2019-01-18 14:08:20
583     599     884  2019-01-18 14:08:20
584     338      10  2019-01-18 14:08:20
585     569     328  2019-01-18 14:08:20
586     123     817  2019-01-18 14:08:20
587     745     849  2019-01-18 14:08:20
588     438     678  2019-01-18 14:08:20

[589 rows x 3 columns]

In [15]:
dfEout.to_csv('edgesSeq.csv', sep=',', index = False)